import { readFile, unlink } from 'node:fs/promises';
import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, randomBytes } from 'node:crypto';
import app from '../src/app.js';
import { pool } from '../src/config/database.js';
import { hashToken } from '../src/lib/passwords.js';

after(() => pool.end());
test('admin product CRUD, validation, rollback and private preview', async () => {
  const tag = 'crud-' + randomUUID();
  const token = randomBytes(32).toString('hex');
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const headers = { Cookie: `maianh_session=${token}`, 'Content-Type': 'application/json', 'X-Requested-With': 'maianh-web' };
  const call = (path, method = 'GET', body, customHeaders = headers) => fetch(base + '/api/' + path, { method, headers: customHeaders, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  let categoryId, userId, id, uploadedFile, avatarFile;
  try {
    const [user] = await pool.execute("INSERT INTO users(email,password_hash,full_name,role) VALUES(?,?,?,'admin')", [tag+'@example.invalid','test-disabled',tag]);
    userId = user.insertId;
    await pool.execute('INSERT INTO auth_sessions(user_id,token_hash,expires_at) VALUES(?,?,UTC_TIMESTAMP()+INTERVAL 1 HOUR)', [userId,hashToken(token)]);
    assert.equal((await call('admin/product-categories','POST',{name:tag},{})).status,401);
    assert.equal((await call('admin/product-categories','POST',{name:tag},{Cookie:headers.Cookie,'Content-Type':'application/json'})).status,403);
    assert.equal((await call('admin/product-categories','POST',{name:'   '})).status,400);
    assert.equal((await call('admin/product-categories','POST',{name:tag,slug:'Invalid Slug'})).status,400);
    await pool.execute("UPDATE users SET role='customer' WHERE id=?",[userId]);
    assert.equal((await call('admin/product-categories','POST',{name:tag})).status,403);
    await pool.execute("UPDATE users SET role='admin' WHERE id=?",[userId]);
    assert.equal((await call('profile','GET',undefined,{})).status,401);
    let profile = await call('profile');
    assert.equal(profile.status,200);
    const initialProfile = (await profile.json()).data;
    assert.ok('cash' in initialProfile.user);
    assert.ok(!('password_hash' in initialProfile.user));
    assert.equal((await call('profile','PATCH',{cash:999999})).status,400);
    assert.equal((await call('profile','PATCH',{full_name:'Profile test',phone:'0912345678'})).status,200);
    assert.equal((await call('profile','PATCH',{phone:'abc'})).status,400);
    const addressBody = {recipient_name:'Test',phone:'0912345678',address_line:'123 Test',ward:'Ward',district:'District',province:'City',is_default:1};
    const addedAddress = await call('profile/addresses','POST',addressBody);
    assert.equal(addedAddress.status,201);
    const addressId = (await addedAddress.json()).data.addresses[0].id;
    assert.equal((await call('profile/addresses','POST',{...addressBody,is_default:0})).status,201);
    let addressRows = (await (await call('profile')).json()).data.addresses;
    const secondary = addressRows.find(a => !a.is_default);
    assert.equal((await call('profile/addresses/'+secondary.id,'PUT',addressBody)).status,200);
    assert.equal((await call('profile/addresses/'+addressId,'DELETE')).status,200);
    assert.equal((await call('profile/addresses/'+secondary.id,'DELETE')).status,200);
    assert.equal((await call('profile/preferences','PATCH',{receive_newsletter:0,receive_sms:1})).status,200);
    assert.equal((await (await call('profile/preferences')).json()).data.receive_sms,1);
    assert.equal((await call('notifications','GET',undefined,{})).status,401);
    const [testNotification]=await pool.execute('INSERT INTO notifications(user_id,kind,title,message) VALUES(?,?,?,?)',[userId,'system','Test notification','Test message']);
    const notificationId=testNotification.insertId;
    assert.equal((await (await call('notifications/unread-count')).json()).data.unread_count,1);
    const notificationList=(await (await call('notifications?unread=1&kind=system')).json()).data;
    assert.equal(notificationList.length,1);
    assert.equal((await call('notifications/'+notificationId+'/read','PATCH',{},{})).status,401);
    assert.equal((await call('notifications/'+notificationId+'/read','PATCH',{})).status,200);
    assert.equal((await (await call('notifications/unread-count')).json()).data.unread_count,0);
    assert.equal((await call('notifications/read-all','PATCH',{})).status,200);
    assert.equal((await call('notifications?kind=invalid')).status,400);
    assert.equal((await call('notifications/18446744073709551615/read','PATCH',{})).status,404);
    const categoryResponse = await call('admin/product-categories','POST',{name:'Gấu lớn '+tag});
    assert.equal(categoryResponse.status,201);
    const category = (await categoryResponse.json()).data;
    categoryId = category.id;
    assert.equal(category.slug,'gau-lon-'+tag);
    assert.equal((await call('admin/product-categories','POST',{name:'Gấu lớn '+tag})).status,409);
    const categoryList = (await (await call('admin/product-categories')).json()).data;
    assert.ok(categoryList.some(item => String(item.id) === String(categoryId)));
    const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j6QAAAABJRU5ErkJggg==','base64');
    const avatarResponse = await fetch(base+'/api/profile/avatar',{method:'POST',headers:{...headers,'Content-Type':'image/png'},body:png});
    assert.equal(avatarResponse.status,201);
    const avatarProfile=(await avatarResponse.json()).data;
    assert.match(avatarProfile.user.avatar_url,/^\/uploads\/avatars\/avatar-[a-f0-9-]+\.png$/);
    avatarFile=new URL('..'+avatarProfile.user.avatar_url,import.meta.url);
    assert.deepEqual(await readFile(avatarFile),png);
    assert.equal(Number(avatarProfile.user.cash),Number(initialProfile.user.cash));
    const addressUpdate=await call('profile','PATCH',{address:'123 Đường mới, Phường A, TP.HCM'});
    assert.equal(addressUpdate.status,200);
    assert.equal((await addressUpdate.json()).data.user.address,'123 Đường mới, Phường A, TP.HCM');
    const upload = (body, custom = {}) => fetch(base + '/api/admin/product-images', { method:'POST', headers:{...headers,'Content-Type':'image/png',...custom},body });
    assert.equal((await upload(png,{Cookie:''})).status,401);
    assert.equal((await upload(png,{'X-Requested-With':''})).status,403);
    assert.equal((await upload(Buffer.from('<html>fake image</html>'))).status,400);
    assert.equal((await upload(Buffer.alloc(5*1024*1024+1))).status,413);
    const imageResponse = await upload(png);
    assert.equal(imageResponse.status,201);
    const imageUrl = (await imageResponse.json()).data.image_url;
    assert.match(imageUrl, /^\/uploads\/products\/product-[a-f0-9-]+\.png$/);
    uploadedFile = new URL('..' + imageUrl, import.meta.url);
    assert.deepEqual(await readFile(uploadedFile),png);
    assert.equal((await fetch(base + imageUrl)).status,200);
    const product = { name: 'Gấu thử', slug: tag, category_id: String(categoryId), description: 'Mô tả', is_active: 1,
      variants: [{sku:tag,size_label:'45cm',color_label:'Nâu',price:100000,compare_at_price:null,stock_quantity:8,is_active:1}], images: [{image_url:imageUrl,alt_text:'Gấu'}] };
    assert.equal((await call('admin/products','POST',product,{})).status,401);
    assert.equal((await call('admin/products','POST',product,{Cookie:headers.Cookie,'Content-Type':'application/json'})).status,403);
    await pool.execute("UPDATE users SET role='customer' WHERE id=?",[userId]);
    assert.equal((await call('admin/products','POST',product)).status,403);
    await pool.execute("UPDATE users SET role='admin' WHERE id=?",[userId]);
    const created = await call('admin/products','POST',product);
    assert.equal(created.status,201,JSON.stringify(await created.clone().json()));
    id = (await created.json()).data.id;
    let detail = (await (await call('admin/products/'+id)).json()).data;
    for (const path of ['admin/me','admin/dashboard','admin/orders','admin/customers']) {
      assert.equal((await call(path)).status,200,path);
    }
    const filtered = await call('admin/products?category_id='+categoryId+'&q='+encodeURIComponent(product.name));
    assert.equal(filtered.status,200);
    const filteredRows = (await filtered.json()).data;
    assert.equal(filteredRows.length,1);
    assert.equal(String(filteredRows[0].id),String(id));
    assert.equal(String(filteredRows[0].category_id),String(categoryId));
    assert.equal((await (await call('admin/products?category_id='+categoryId+'&q=not-found-'+tag)).json()).data.length,0);
    assert.equal((await (await call('admin/products?category_id=18446744073709551615')).json()).data.length,0);
    assert.ok((await (await call('admin/products')).json()).data.some(p => String(p.id) === String(id)));
    for (const query of ['category_id=abc','category_id=0','category_id=1&category_id=2','q=a&q=b']) {
      assert.equal((await call('admin/products?'+query)).status,400);
    }
    const variantId = detail.variants[0].id;
    const relatedResponse=await call('products/'+id+'/related');
    assert.equal(relatedResponse.status,200);
    const relatedRows=(await relatedResponse.json()).data;
    assert.ok(relatedRows.length<=4);
    assert.ok(relatedRows.every(p=>String(p.id)!==String(id) && p.variant_id));
    assert.equal((await call('products/0/related')).status,400);

    const suggestionsResponse=await call('cart/suggestions');
    assert.equal(suggestionsResponse.status,200);
    const suggestions=(await suggestionsResponse.json()).data;
    assert.ok(suggestions.length<=4);
    assert.ok(suggestions.every(p=>p.variant_id && Number(p.stock)>0));

    assert.equal((await call('home/wishlist','GET',undefined,{})).status,401);
    assert.equal((await call('home/wishlist/'+id,'POST',{})).status,200);
    assert.equal((await call('home/wishlist/'+id,'POST',{})).status,200);
    let favorites=(await (await call('home/wishlist')).json()).data;
    assert.equal(favorites.length,1);
    assert.equal(String(favorites[0].id),String(id));
    assert.equal(favorites[0].image_url,imageUrl);
    assert.equal((await call('home/wishlist/'+id,'DELETE')).status,200);
    assert.equal((await (await call('home/wishlist')).json()).data.length,0);
    assert.equal((await call('home/wishlist/0','POST',{})).status,400);

    assert.equal((await call('cart','POST',{variant_id:variantId,quantity:1},{})).status,401);
    const addCart = () => call('cart','POST',{variant_id:variantId,quantity:1});
    assert.equal((await addCart()).status,201);
    const additions = await Promise.all([addCart(),addCart()]);
    assert.ok(additions.every(response => response.status === 201));
    let cartRows = (await (await call('cart')).json()).data;
    assert.equal(cartRows.length,1);
    assert.equal(Number(cartRows[0].quantity),3);
    assert.ok(!(await (await call('cart/suggestions')).json()).data.some(p=>String(p.id)===String(id)));
    assert.equal((await call('cart','POST',{variant_id:variantId,quantity:6})).status,400);
    assert.equal((await call('cart','POST',{variant_id:variantId,quantity:0})).status,400);
    cartRows = (await (await call('cart')).json()).data;
    assert.equal(Number(cartRows[0].quantity),3);
    await pool.execute('UPDATE products SET is_active=0 WHERE id=?',[id]);
    assert.equal((await addCart()).status,404);
    await pool.execute('UPDATE products SET is_active=1 WHERE id=?',[id]);
    assert.equal((await call('cart/'+variantId,'DELETE')).status,200);
    await addCart();
    const paymentBody={key:randomUUID(),method:'store_pay',items:[{variant_id:variantId,quantity:1}],coupons:[],expected_total:130000,address:{full_name:'Test',phone:'0912345678',address:'123 Test'}};
    assert.equal((await call('checkout','POST',paymentBody)).status,409);
    await pool.execute('UPDATE users SET cash=500000 WHERE id=?',[userId]);
    assert.equal((await call('checkout','POST',{...paymentBody,expected_total:1})).status,409);
    const paid=await call('checkout','POST',paymentBody);
    assert.equal(paid.status,201,JSON.stringify(await paid.clone().json()));
    const paidOrder=(await paid.json()).data;
    assert.equal((await call('checkout','POST',paymentBody)).status,200);
    const [[wallet]]=await pool.execute('SELECT cash FROM users WHERE id=?',[userId]);
    assert.equal(Number(wallet.cash),370000);
    const [[payment]]=await pool.execute('SELECT status,method,amount FROM payments WHERE order_id=?',[paidOrder.id]);
    assert.equal(payment.status,'paid');assert.equal(payment.method,'store_pay');assert.equal(Number(payment.amount),130000);
    assert.equal((await (await call('cart')).json()).data.length,0);
    const orderDetailResponse=await call('profile/orders/'+paidOrder.id);
    assert.equal(orderDetailResponse.status,200);
    const orderDetail=(await orderDetailResponse.json()).data;
    assert.equal(orderDetail.recipient_phone,'0912345678');
    assert.equal(orderDetail.shipping_address,'123 Test');
    assert.equal(orderDetail.items.length,1);
    assert.equal(Number(orderDetail.items[0].unit_price),100000);
    assert.equal(orderDetail.items[0].image_url,imageUrl);
    assert.equal((await call('profile/orders/'+paidOrder.id,'GET',undefined,{})).status,401);
    await pool.execute("UPDATE orders SET status='confirmed' WHERE id=?",[paidOrder.id]);
    assert.equal((await call('profile/orders/'+paidOrder.id+'/cancel','POST',{})).status,409);
    await pool.execute("UPDATE orders SET status='pending' WHERE id=?",[paidOrder.id]);
    const [[beforeCancel]]=await pool.execute('SELECT stock_quantity FROM product_variants WHERE id=?',[variantId]);
    const cancelResults=await Promise.all([call('profile/orders/'+paidOrder.id+'/cancel','POST',{}),call('profile/orders/'+paidOrder.id+'/cancel','POST',{})]);
    assert.deepEqual(cancelResults.map(r=>r.status).sort(),[200,409]);
    const [[afterCancel]]=await pool.execute('SELECT stock_quantity FROM product_variants WHERE id=?',[variantId]);
    assert.equal(Number(afterCancel.stock_quantity),Number(beforeCancel.stock_quantity)+1);
    const [[refundedUser]]=await pool.execute('SELECT cash FROM users WHERE id=?',[userId]);
    assert.equal(Number(refundedUser.cash),500000);
    const [refunds]=await pool.execute('SELECT status,amount FROM refunds WHERE order_id=?',[paidOrder.id]);
    assert.equal(refunds.length,1);assert.equal(refunds[0].status,'completed');assert.equal(Number(refunds[0].amount),130000);
    await pool.execute('DELETE FROM orders WHERE id=?',[paidOrder.id]);


    assert.equal(detail.images.length,1);
    assert.equal(detail.images[0].image_url,imageUrl);
    assert.equal((await call('products/'+id)).status,200);
    assert.equal((await call('admin/products','POST',product)).status,409);
    assert.equal((await call('admin/products/'+id,'PUT',{...product,variants:[{...product.variants[0],price:-1}]})).status,400);
    assert.equal((await call('admin/products/'+id,'PUT',{...product,name:'Must rollback',variants:[{...product.variants[0],id:'18446744073709551615'}]})).status,400);
    detail = (await (await call('admin/products/'+id)).json()).data;
    assert.equal(detail.name, product.name);
    const updated = {...product,name:'Gấu đã sửa',is_active:0,variants:[{...product.variants[0],id:String(variantId),price:200000,stock_quantity:3}]};
    assert.equal((await call('admin/products/'+id,'PUT',updated)).status,200);
    detail = (await (await call('admin/products/'+id)).json()).data;
    assert.equal(String(detail.variants[0].id),String(variantId));
    assert.equal(Number(detail.variants[0].price),200000);
    assert.equal((await call('products/'+id)).status,404);
    assert.equal((await call('admin/products/'+id)).status,200);
    assert.equal((await call('admin/products/'+id,'DELETE',{})).status,200);
    assert.equal((await call('admin/products/'+id)).status,404);
    const [variants] = await pool.execute('SELECT id FROM product_variants WHERE product_id=?',[id]);
    assert.equal(variants.length,0);
  } finally {
    if (uploadedFile) await unlink(uploadedFile);
    if (avatarFile) await unlink(avatarFile);
    if (userId) await pool.execute('DELETE FROM orders WHERE user_id=?',[userId]);
    if (id) await pool.execute('DELETE FROM products WHERE id=?',[id]);
    if (categoryId) await pool.execute('DELETE FROM categories WHERE id=?',[categoryId]);
    if (userId) await pool.execute('DELETE FROM users WHERE id=?',[userId]);
    server.closeAllConnections();
    await new Promise(resolve => server.close(resolve));
  }
});
