(() => {
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let page=1,busy=false,uploads=[];
async function api(path='',options={}){const r=await fetch('/api/admin/posts'+path,{credentials:'same-origin',...options,headers:{'X-Requested-With':'maianh-web',...options.headers}});const j=await r.json();if(!r.ok)throw Error(j.error||'Không thực hiện được yêu cầu.');return j;}
const status=document.createElement('p');status.setAttribute('role','status');$('postsList').before(status);const pager=document.createElement('div');pager.className='ap-pager';$('postsList').after(pager);
async function load(){status.textContent='Đang tải…';try{const r=await api('?page='+page+'&limit=20');$('postsList').innerHTML=r.data.map(p=>`<article class="ap-row"><img class="ap-avatar" src="${esc(p.avatar_url||'/images/store-logo.svg')}" alt=""><div class="ap-copy"><strong>${esc(p.title)}</strong><small>${esc(p.author_name)} · ${esc(p.category_name)} · ${esc(p.created_at)} · ${p.attachments.length} file</small></div><button class="icon-action" data-view="${p.id}" aria-label="Xem chi tiết"><i class="fas fa-eye"></i></button><button class="icon-action danger" data-remove="${p.id}" aria-label="Xóa bài viết"><i class="fas fa-trash"></i></button></article>`).join('')||'<p>Chưa có bài viết.</p>';status.textContent=r.pagination.total+' bài viết';pager.innerHTML=`<button class="btn-primary" data-prev ${page===1?'disabled':''}>← Trước</button><span>Trang ${page}</span><button class="btn-primary" data-next ${page>=r.pagination.totalPages?'disabled':''}>Sau →</button>`;}catch(e){status.textContent=e.message;}}
pager.onclick=e=>{if(e.target.closest('[data-prev]')){page--;load();}if(e.target.closest('[data-next]')){page++;load();}};
const dialog=document.createElement('dialog');dialog.className='ap-dialog';dialog.setAttribute('aria-label','Bài viết');document.body.append(dialog);dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
function shell(content){dialog.innerHTML='<button type="button" class="ap-close" aria-label="Đóng">×</button>'+content;dialog.querySelector('.ap-close').onclick=()=>{if(!busy)dialog.close();};dialog.showModal();}
function filesHtml(files){return files.map(f=>{const url=esc(f.file_url);return `<div class="ap-file">${f.kind==='image'?`<img src="${url}" alt="${esc(f.original_name)}">`:f.kind==='video'?`<video controls preload="metadata" src="${url}"></video>`:''}<a href="${url}" target="_blank" rel="noopener">📎 ${esc(f.original_name)}</a></div>`;}).join('');}
$('postsList').onclick=async e=>{const b=e.target.closest('[data-view],[data-remove]');if(!b)return;try{if(b.dataset.view){const {data:p}=await api('/'+b.dataset.view);shell(`<h2>${esc(p.title)}</h2><p>${esc(p.author_name)} · ${esc(p.category_name)}</p><div class="ap-content">${esc(p.content)}</div><div class="ap-files">${filesHtml(p.attachments)}</div>`);}else{if(!confirm('Xóa bài viết và các file đính kèm? Thao tác này không thể hoàn tác.'))return;b.disabled=true;await api('/'+b.dataset.remove,{method:'DELETE',headers:{'Content-Type':'application/json'},body:'{}'});await load();}}catch(e){status.textContent=e.message;b.disabled=false;}};
$('addPostBtn').onclick=async()=>{try{const {data}=await api('/categories');uploads=[];shell(`<h2>Đăng bài · hongquy sờtore</h2><p>Bài viết xuất hiện ngay trên Tin tức với logo cửa hàng.</p><form id="apForm"><label>Tiêu đề<input name="title" required maxlength="255"></label><label>Chủ đề<select name="category_id">${data.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label><label>Nội dung<textarea name="content" required maxlength="20000" rows="7"></textarea></label><label>File đính kèm · tối đa 10 file, 25 MB/file<input type="file" id="apFiles" multiple accept=".jpg,.jpeg,.png,.webp,.mp4,.webm,.pdf,.docx,.xlsx,.pptx"></label><div id="apSelected"></div><p id="apError" role="alert"></p><button type="submit" class="btn-primary">Đăng ngay</button></form>`);
$('apFiles').onchange=()=>{$('apSelected').textContent=Array.from($('apFiles').files).map(f=>f.name).join(' · ');};
$('apForm').onsubmit=async e=>{e.preventDefault();if(busy)return;const fs=Array.from($('apFiles').files);if(fs.length>10||fs.some(f=>f.size>25*1024*1024)){ $('apError').textContent='Tối đa 10 file, mỗi file không quá 25 MB.';return;}busy=true;const fields=Object.fromEntries(new FormData(e.target));dialog.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=true);try{for(let i=0;i<fs.length;i++){if(uploads[i]?.file===fs[i])continue;$('apError').textContent='Đang tải '+fs[i].name;const {data}=await api('/uploads',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(fs[i].name)},body:fs[i]});uploads[i]={file:fs[i],id:data.id};}await api('',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:fields.title,content:fields.content,category_id:fields.category_id,attachment_ids:uploads.slice(0,fs.length).map(f=>f.id)})});dialog.close();page=1;await load();}catch(e){$('apError').textContent=e.message;}finally{busy=false;dialog.querySelectorAll('button,input,textarea,select').forEach(el=>el.disabled=false);}};
}catch(e){status.textContent=e.message;}};load();
})();
