(() => {
const $=id=>document.getElementById(id),esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const columns=['id','external_id','category_id','korean','romanization','vietnamese','word_type','example_ko','example_vi','level','audio_url','is_active','last_import_id','created_at','updated_at'];
const labels={external_id:'Mã từ vựng',category_id:'Chủ đề',korean:'Tiếng Hàn',romanization:'Phiên âm',vietnamese:'Nghĩa tiếng Việt',word_type:'Từ loại',example_ko:'Ví dụ tiếng Hàn',example_vi:'Dịch ví dụ',level:'Trình độ',audio_url:'URL âm thanh',is_active:'Hiển thị'};
let rows=[],categories=[],page=1,version=0,editing=null,busy=false;
async function api(path='',method='GET',body){const r=await fetch('/api/admin/vocabulary'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-Requested-With':'maianh-web'},...(body?{body:JSON.stringify(body)}:{})});const j=await r.json();if(!r.ok)throw Error(j.error||'Không thực hiện được yêu cầu.');return j;}
$('vocabHead').innerHTML='<tr>'+columns.map(c=>'<th>'+c+'</th>').join('')+'<th>Thao tác</th></tr>';
async function load(){const v=++version;$('vocabStatus').textContent='Đang tải…';try{const result=await api('?page='+page+'&q='+encodeURIComponent($('vocabSearch').value.trim()));if(v!==version)return;rows=result.data;
$('vocabTableBody').innerHTML=rows.map(r=>'<tr>'+columns.map(c=>'<td>'+esc(r[c])+(c==='category_id'?'<small>'+esc(r.category_name)+'</small>':'')+'</td>').join('')+`<td><div class="table-actions"><button class="icon-action" data-edit="${r.id}" aria-label="Sửa ${esc(r.korean)}"><i class="fas fa-edit"></i></button><button class="icon-action danger" data-delete="${r.id}" aria-label="Xóa ${esc(r.korean)}"><i class="fas fa-trash"></i></button></div></td></tr>`).join('')||'<tr><td colspan="16">Không tìm thấy từ vựng.</td></tr>';
$('vocabStatus').textContent=result.total+' từ vựng';$('vocabPage').textContent='Trang '+page+' / '+Math.max(1,Math.ceil(result.total/25));$('vocabPrev').disabled=page===1;$('vocabNext').disabled=page*25>=result.total;
}catch(e){if(v===version)$('vocabStatus').textContent=e.message;}}
const dialog=document.createElement('dialog');dialog.className='vocab-dialog';dialog.innerHTML='<form><div class="vocab-heading"><h2 id="vocabTitle">Từ vựng tiếng Hàn</h2><button type="button" data-close aria-label="Đóng">×</button></div><div class="vocab-fields"></div><p role="alert" class="vocab-error"></p><div class="vocab-pages"><button type="button" data-close class="btn-primary">Hủy</button><button type="submit" class="btn-primary">Lưu từ vựng</button></div></form>';dialog.setAttribute('aria-labelledby','vocabTitle');document.body.append(dialog);
async function open(row){try{categories=(await api('/categories')).data;}catch(e){$('vocabStatus').textContent=e.message;return;}editing=row?.id||null;$('vocabTitle').textContent=editing?'Chỉnh sửa từ vựng':'Thêm từ vựng';dialog.querySelector('.vocab-error').textContent='';
dialog.querySelector('.vocab-fields').innerHTML=Object.entries(labels).map(([key,label])=>{let field;if(key==='category_id')field='<select name="category_id" required>'+categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')+'</select>';else if(key==='level')field='<select name="level"><option value="beginner">Sơ cấp</option><option value="intermediate">Trung cấp</option><option value="advanced">Cao cấp</option></select>';else if(key==='is_active')field='<select name="is_active"><option value="1">Hiện</option><option value="0">Ẩn</option></select>';else{const max={external_id:100,korean:255,romanization:255,word_type:80,audio_url:1024}[key]||16000;field=['vietnamese','example_ko','example_vi'].includes(key)?`<textarea name="${key}" maxlength="${max}" ${key==='vietnamese'?'required':''}></textarea>`:`<input name="${key}" maxlength="${max}" ${['external_id','korean'].includes(key)?'required':''}>`;}return `<label>${label}<small>${key}</small>${field}</label>`;}).join('');if(row)for(const key of Object.keys(labels))dialog.querySelector(`[name="${key}"]`).value=row[key]??'';dialog.showModal();}
dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{if(!busy)dialog.close();});dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const button=dialog.querySelector('[type="submit"]');button.disabled=true;try{const body=Object.fromEntries(new FormData(e.target));body.is_active=Number(body.is_active);await api(editing?'/'+editing:'',editing?'PUT':'POST',body);dialog.close();await load();}catch(e){dialog.querySelector('.vocab-error').textContent=e.message;}finally{busy=false;button.disabled=false;}};
$('addVocabBtn').onclick=()=>open();$('vocabTableBody').onclick=async e=>{const b=e.target.closest('[data-edit],[data-delete]');if(!b)return;const r=rows.find(r=>String(r.id)===(b.dataset.edit||b.dataset.delete));if(b.dataset.edit)return open(r);if(!confirm('Xóa từ “'+r.korean+'”? Tiến độ và lượt luyện tập liên quan cũng bị xóa. Bạn có thể chọn Ẩn khi sửa để giữ lịch sử.'))return;b.disabled=true;try{await api('/'+r.id,'DELETE',{});await load();}catch(e){$('vocabStatus').textContent=e.message;b.disabled=false;}};
let timer;$('vocabSearch').oninput=()=>{clearTimeout(timer);version++;timer=setTimeout(()=>{page=1;load();},250);};$('vocabPrev').onclick=()=>{page--;load();};$('vocabNext').onclick=()=>{page++;load();};load();
})();
